# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8573d4a7e77beb8be09452da7e4200347c9619acb98470a8bd11919207f95d482312a1b280e0c14e91713e004d2684d76f982f4fd67c57c6b62c8dfd085fc5b

test:
  secret_key_base: 556b29cd55812e671f76ba9ccab3a2e66eaa5b319da9684ca9db4a50e8b62eee620482d8978c8b6708ccfd3facf9a72a45446adc44342d44a8de2cdbad053f82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
